### ISSUE TITLE
Adding our work

### ISSUE THREAD

**Issue by Shar-01** [IBM/model-reprogramming#1]
Thank you for creating this repository. We would like to add a recent work here. 

**Paper title**: Enhancing Joint Motion Prediction for Individuals with Limb Loss Through Model Reprogramming

**Author list**: Sharmita Dey, Sarath R. Nair

**Paper link**: https://arxiv.org/abs/2403.06569

**Publication venue (arxiv is fine) and year**: International Conference on Learning Representations (ICLR) Workshop 2024: Learning from Time Series for Health

**Bibtex citation format:**  @article{dey2024enhancing,
  title={Enhancing Joint Motion Prediction for Individuals with Limb Loss Through Model Reprogramming},
  author={Dey, Sharmita and Nair, Sarath R},
  journal={arXiv preprint arXiv:2403.06569},
  year={2024}
}

**Source domain:** General human motion

**Source model:** Temporal CNN

**Target domain:** Prosthesis motion for individuals with limb loss

**Highlights:** Adapt motion models, originally designed for able-bodied individuals to forecast joint motion for prosthesis for individuals with limb loss. 

Let us know if any changes are required.
Thanks a lot for your time!

**Comment by pinyuchen** [comment]
Done! Congrats!

**Comment by Shar-01** [comment]
Thanks a lot! Closing the issue.
